# .scrutinizer.yml
filter:
    excluded_paths:
        - 'apachetika/1.2/*'
        - 'apachetika/1.5/*'
        - 'archive/7z/*'
        - 'autosize/v1.18.4/*'
        - 'autosize/v1.18.9/*'
        - 'barcode/fonts/*'
        - 'barcode/phpbarcode/*'
        - 'barcode/phpqrcode/*'
        - 'calendarpicker/doc/*'
        - 'calendarpicker/lang/*'
        - 'calendarpicker/skins/*'
        - 'ckeditor/adapters/*'
        - 'ckeditor/images/*'
        - 'ckeditor/lang/*'
        - 'ckeditor/plugins/*'
        - 'ckeditor/skins/*'
        - 'ckeditor/themes/*'
        - 'codemirror/*'
        - 'csstoinline/csstoinline/*'
        - 'csstoinline/emogrifier/*'
        - 'docoffice/jodconverter/*'
        - 'dompdf/0.6.0b3/*'
        - 'fancybox/1.3.4/*'
        - 'firephp/FirePHPCore-0.3.2/*'
        - 'flexpaper/1.4.5/*'
        - 'flvplayer/1.6.0/*'
        - 'gantt/lib/*'
        - 'hclean/jssanitize/*'
        - 'hclean/purifier4.3.0/*'
        - 'hljs/7.3/*'
        - 'html2text/*'
        - 'iban/php-iban-1.1.2/*'
        - 'iban/php-iban-1.4.7/*'
        - 'jqcolorpicker/2.0/*'
        - 'jqdatepick/v4.0.6/*'
        - 'jqplot/jquery.jqplot.1.0.0b2_r1012/*'
        - 'jquery/1.7.1/*'
        - 'jqueryui/1.8.2/*'
        - 'jsgauge/0.4.1/*'
        - 'keyboard/1.28/*'
        - 'location/4.1/*'
        - 'location/6.0/*'
        - 'location/js/*'
        - 'markdown/1.0.1/*'
        - 'markdown/extra-1.2.5/*'
        - 'mejs/2.11.0.0/*'
        - 'modbus/_lib/*'
        - 'ograph/open-graph-protocol-tools/*'
        - 'orgchart/lib/*'
        - 'pear/File/*'
        - 'phpmailer/5.1/*'
        - 'phpmailer/5.2/*'
        - 'phpmailer/5.2.8/*'
        - 'punymce/js/*'
        - 'sass/phpsass/*'
        - 'swf/2.2/*'
        - 'toast/0.3.0f/*'
        - 'tooltip/lib/*'
        - 'tremol/linux/*'
        - 'xmpphp/0.1rc2-r77/*'
        - 'chromephp/ChromePHP.class.php'
        - 'avatar/Avatarco.class.php'
        - 'ckeditor/ckeditor_php4.php'
        - 'ckeditor/ckeditor_php5.php'
        - 'ckeditor/ckeditor.php'
